In [86]:
import numpy as np
import math
from sklearn import datasets
from sklearn import preprocessing
from scipy.special import expit

In [87]:
#load development data
house_price_train = [[240,2],[260,2],[260,3],[360,2],[420,1],[350,2],[285,1]]
size_train = [1200,1400,1900,2600,2700,2400,1150]

house_sk_data = datasets.load_boston()
# side of training and cross validation sets
m_train = 400
m_cv = 506 - m_train

# training set, using features:
# B 1000(Bk - 0.63)^2, LSTAT % lower status of the population
# scaled for zero mean and unit variance
house_sk_train = preprocessing.scale(house_sk_data.data[:m_train, 10:12])
print(house_sk_train.shape)

# cross validation set
house_sk_target = house_sk_data.target[:m_train]
house_sk_target.shape

(400, 2)


(400,)

In [88]:
# creating: neural net for regression
# backpropagation from scratch
# Training on m=7 examples, 2 features
# 1 hidden layer, 2 nodes, ReLu activation
# MSE loss function, no regularization

#randomly initialize weights for first and second layer
weights = np.random.rand(2,3)
weights2 = np.random.rand(1,3)

feat_bias = np.column_stack([np.ones((m_train, 1)), house_sk_train])

# initialize gradient accumulator
big_delta = np.zeros([2,1,1])

In [89]:
# Forward propagates for a given training example _i_
def propagate(i):
    global weights2, weights

    #learning rate
    a = 0.5

    # z for second layer and activation (ReLu)
    z2 = np.dot(weights, np.transpose(feat_bias[i, :]))
    a2 = expit(z2)
    #a2 = np.maximum(0, z2)
    # add bias unit for second layer
    a2_bias = np.concatenate((np.ones(1), a2))
    print(a2_bias)
    # z for third layer and final activation (ReLu)
    z3 = np.dot(weights2, a2_bias)
    hypot = z3
    #hypot = np.maximum(0, z3)

    print(f'Prediction: {z3}')

    # Backpropagates to accumulate partials and deltas
    # Delta for third layer (mean squared error)
    delta3 =  house_sk_target[i] - hypot
    # derivative of error w.r.t weights, second layer
    layer2partials = np.multiply(delta3, a2_bias)

    # derivative of error w.r.t weights, first layer
    # big_delta2 without bias
    delta2 = np.multiply(delta3, a2)
    delta2_matrix = np.column_stack([delta2, delta2, delta2])
    feat_bias_matrix = np.row_stack([feat_bias[i,:], feat_bias[i,:]])
    layer1partials = np.multiply(delta2_matrix, feat_bias_matrix)

    weights2 = weights2 - a*layer2partials
    weights = weights - a*layer1partials

def sigmoid(x):
  return 1 / (1 + math.exp(-x))

In [90]:
for i in range(0, m_train):
    propagate(i)

[1.         0.41535249 0.49358374]
Prediction: [1.11016403]
[1.         0.00250581 0.00191392]
Prediction: [-10.89403034]
[1.         0.00289346 0.00213347]
Prediction: [-27.14402319]
[1.         0.02936509 0.04267907]
Prediction: [-58.38630858]
[1.         0.00500271 0.00353041]
Prediction: [-103.98981961]
[1.         0.00382405 0.0030142 ]
Prediction: [-174.07624031]
[1.00000000e+00 3.24216456e-07 2.85886787e-08]
Prediction: [-275.41882934]
[1.00000000e+00 2.97128361e-07 2.64769664e-08]
Prediction: [-424.57824382]
[1.00000000e+00 5.91219335e-07 4.85395067e-08]
Prediction: [-650.41736786]
[1.00000000e+00 5.87753828e-07 4.83088144e-08]
Prediction: [-983.87605177]
[1.00000000e+00 3.97893649e-07 3.42830903e-08]
Prediction: [-1485.26407628]
[1.00000000e+00 2.96441617e-07 2.64718128e-08]
Prediction: [-2235.39611367]
[1.00000000e+00 4.54795108e-07 3.86180612e-08]
Prediction: [-3362.54417167]
[1.         0.39311617 0.72331945]
Prediction: [-5062.64342605]
[1. 0. 0.]
Prediction: [-7596.187967